# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gsis_name', models.CharField(db_index=True, max_length=75, null=True)),
                ('full_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(choices=[(b'C', b'Center'), (b'CB', b'Cornerback'), (b'DB', b'Defensive Back'), (b'DE', b'Defensive End'), (b'DL', b'Defensive Lineman'), (b'FB', b'Fullback'), (b'FS', b'Free Safety'), (b'G', b'Guard'), (b'ILB', b'Inside Linebacker'), (b'K', b'Kicker'), (b'LB', b'Linebacker'), (b'LS', b'Long Snapper'), (b'MLB', b'MIddle Linebacker'), (b'NT', b'Nose Tackle'), (b'OG', b'Outside Guard'), (b'OL', b'Offensive Lineman'), (b'OLB', b'Outside Linebacker'), (b'OT', b'Offensive Tackle'), (b'P', b'Punter'), (b'QB', b'Quarterback'), (b'RB', b'Runningback'), (b'SAF', b'SAF'), (b'SS', b'Strong Safety'), (b'T', b'Tackle'), (b'TE', b'Tight End'), (b'WR', b'Wide Receiver'), (b'UNK', b'Unknown')], max_length=3)),
                ('profile_id', models.IntegerField(null=True)),
                ('profile_url', models.CharField(max_length=255, null=True)),
                ('uniform_number', models.SmallIntegerField(null=True)),
                ('birthdate', models.CharField(max_length=75, null=True)),
                ('college', models.CharField(max_length=255, null=True)),
                ('height', models.SmallIntegerField(null=True)),
                ('weight', models.SmallIntegerField(null=True)),
                ('years_pro', models.SmallIntegerField(null=True)),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'InjuredReserve', b'Injured Reserve'), (b'NonFootballInjury', b'Non-football Injury'), (b'Suspended', b'Suspended'), (b'PUP', b'PUP'), (b'UnsignedDraftPick', b'Unsigned Draft Pick'), (b'Exempt', b'Exempt'), (b'Unknown', b'Unknown')], max_length=18)),
            ],
            options={
                'ordering': ['position', 'last_name', 'first_name'],
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['team_id'],
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(db_column=b'team', on_delete=django.db.models.deletion.PROTECT, to='football.Team'),
        ),
    ]
