# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_userteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userteam',
            old_name='user_id',
            new_name='user',
        ),
    ]
