# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20170322_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.UserTeam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Player')),
            ],
            options={
                'ordering': ['fantasy_team', 'player'],
            },
        ),
    ]
