# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_fantasystats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasystats',
            name='player',
        ),
        migrations.DeleteModel(
            name='FantasyStats',
        ),
    ]
